import json

sintomas = [
    "itching",
    "skin_rash",
    "nodal_skin_eruptions",
    "continuous_sneezing",
    "shivering",
    "chills",
    "joint_pain",
    "stomach_pain",
    "acidity",
    "ulcers_on_tongue",
    "muscle_wasting",
    "vomiting",
    "burning_micturition",
    "spotting_urination",
    "fatigue",
    "weight_gain",
    "anxiety",
    "cold_hands_and_feets",
    "mood_swings",
    "weight_loss",
    "restlessness",
    "lethargy",
    "patches_in_throat",
    "irregular_sugar_level",
    "cough",
    "high_fever",
    "sunken_eyes",
    "breathlessness",
    "sweating",
    "dehydration",
    "indigestion",
    "headache",
    "yellowish_skin",
    "dark_urine",
    "nausea",
    "loss_of_appetite",
    "pain_behind_the_eyes",
    "back_pain",
    "constipation",
    "abdominal_pain",
    "diarrhoea",
    "mild_fever",
    "yellow_urine",
    "yellowing_of_eyes",
    "acute_liver_failure",
    "fluid_overload",
    "swelling_of_stomach",
    "swelled_lymph_nodes",
    "malaise",
    "blurred_and_distorted_vision",
    "phlegm",
    "throat_irritation",
    "redness_of_eyes",
    "sinus_pressure",
    "runny_nose",
    "congestion",
    "chest_pain",
    "weakness_in_limbs",
    "fast_heart_rate",
    "pain_during_bowel_movements",
    "pain_in_anal_region",
    "bloody_stool",
    "irritation_in_anus",
    "neck_pain",
    "dizziness",
    "cramps",
    "bruising",
    "obesity",
    "swollen_legs",
    "swollen_blood_vessels",
    "puffy_face_and_eyes",
    "enlarged_thyroid",
    "brittle_nails",
    "swollen_extremeties",
    "excessive_hunger",
    "extra_marital_contacts",
    "drying_and_tingling_lips",
    "slurred_speech",
    "knee_pain",
    "hip_joint_pain",
    "muscle_weakness",
    "stiff_neck",
    "swelling_joints",
    "movement_stiffness",
    "spinning_movements",
    "loss_of_balance",
    "unsteadiness",
    "weakness_of_one_body_side",
    "loss_of_smell",
    "bladder_discomfort",
    "foul_smell_ofurine",
    "continuous_feel_of_urine",
    "passage_of_gases",
    "internal_itching",
    "toxic_look_(typhos)",
    "depression",
    "irritability",
    "muscle_pain",
    "altered_sensorium",
    "red_spots_over_body",
    "belly_pain",
    "abnormal_menstruation",
    "dischromic_patches",
    "watering_from_eyes",
    "increased_appetite",
    "polyuria",
    "family_history",
    "mucoid_sputum",
    "rusty_sputum",
    "lack_of_concentration",
    "visual_disturbances",
    "receiving_blood_transfusion",
    "receiving_unsterile_injections",
    "coma",
    "stomach_bleeding",
    "distention_of_abdomen",
    "history_of_alcohol_consumption",
    "fluid_overload.1",
    "blood_in_sputum",
    "prominent_veins_on_calf",
    "palpitations",
    "painful_walking",
    "pus_filled_pimples",
    "blackheads",
    "scurring",
    "skin_peeling",
    "silver_like_dusting",
    "small_dents_in_nails",
    "inflammatory_nails",
    "blister",
    "red_sore_around_nose",
    "yellow_crust_ooze"
]


skin_related_symptoms = ["itching", "skin_rash", "nodal_skin_eruptions", "patches_in_throat", "yellowish_skin", "yellowing_of_eyes", "red_spots_over_body", "dischromic_patches", "peeling_skin", "silver_like_dusting", "small_dents_in_nails", "inflammatory_nails", "blister", "red_sore_around_nose", "yellow_crust_ooze"]
respiratory_symptoms = ["continuous_sneezing", "coughing", "phlegm", "throat_irritation", "sinus_pressure", "runny_nose", "congestion", "chest_pain", "breathlessness"]
gastrointestinal_symptoms = ["stomach_pain", "acidity", "ulcers_on_tongue", "muscle_wasting", "vomiting", "burning_micturition", "spotting_urination", "indigestion", "nausea", "loss_of_appetite", "abdominal_pain", "diarrhoea", "constipation", "swelling_of_stomach", "bloody_stool", "irritation_in_anus"]
musculoskeletal_symptoms = ["joint_pain", "muscle_weakness", "stiff_neck", "swelling_joints", "movement_stiffness", "spinning_movements", "loss_of_balance", "unsteadiness", "weakness_of_one_body_side", "knee_pain", "hip_joint_pain", "muscle_weakness", "painful_walking", "back_pain"]
general_symptoms = ["shivering", "chills", "high_fever", "mild_fever", "fatigue", "weight_gain", "weight_loss", "anxiety", "mood_swings", "restlessness", "lethargy", "sunken_eyes", "sweating", "dehydration", "headache", "dark_urine", "nausea", "loss_of_appetite", "pain_behind_the_eyes", "malaise", "blurred_and_distorted_vision", "weakness_in_limbs", "fast_heart_rate", "dizziness", "cramps", "bruising", "obesity", "swollen_legs", "swollen_blood_vessels", "puffy_face_and_eyes", "enlarged_thyroid", "brittle_nails", "swollen_extremeties", "excessive_hunger", "extra_marital_contacts", "drying_and_tingling_lips", "slurred_speech", "palpitations", "pus_filled_pimples", "blackheads", "scurring", "skin_peeling", "prominent_veins_on_calf", "neck_pain"]
cardiovascular_symptoms = ["fast_heart_rate", "palpitations", "chest_pain", "breathlessness", "fluid_overload", "swelling_of_legs", "swollen_blood_vessels", "prominent_veins_on_calf"]
neurological_symptoms = ["weakness_in_limbs", "movement_stiffness", "spinning_movements", "loss_of_balance", "unsteadiness", "weakness_of_one_body_side", "blurred_and_distorted_vision", "visual_disturbances", "loss_of_smell", "lack_of_concentration", "altered_sensorium", "depression", "irritability", "muscle_pain", "malaise", "dizziness", "cramps", "neck_pain", "redness_of_eyes", "sinus_pressure"]
urogenital_symptoms = ["burning_micturition", "spotting_urination", "fluid_overload", "bladder_discomfort", "continuous_feel_of_urine", "passage_of_gases", "foul_smell_of_urine", "bloody_stool", "yellow_urine", "yellowing_of_eyes"]
liver_related_symptoms = ["jaundice", "yellowing_of_eyes", "yellow_urine", "abdominal_pain", "distention_of_abdomen", "toxic_look_(typhos)", "acute_liver_failure", "swelling_of_stomach", "swelled_lymph_nodes"]
metabolic_symptoms = ["weight_gain", "weight_loss", "irregular_sugar_level", "excessive_hunger", "dehydration", "indigestion", "fatigue", "weakness"]
hematological_symptoms = ["receiving_blood_transfusion", "receiving_unsterile_injections", "blood_in_sputum", "stomach_bleeding", "mucoid_sputum", "rusty_sputum"]


#make a dictionary of categories and symptoms

categorias = {"skin_related_symptoms": skin_related_symptoms, "respiratory_symptoms": respiratory_symptoms, "gastrointestinal_symptoms": gastrointestinal_symptoms, "musculoskeletal_symptoms": musculoskeletal_symptoms, "general_symptoms": general_symptoms, "cardiovascular_symptoms": cardiovascular_symptoms, "neurological_symptoms": neurological_symptoms, "urogenital_symptoms": urogenital_symptoms, "liver_related_symptoms": liver_related_symptoms, "metabolic_symptoms": metabolic_symptoms, "hematological_symptoms": hematological_symptoms}


#load traduccion.json file

with open('traduccion.json') as json_file:
    traduccion = json.load(json_file)
